# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    tags:
      - 'v*'

run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm i
      - run: npm ci
      - run: npm test

  publish-npm:
    name: Publish to NPM
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: |
          npm i
          npm ci
          npm run build
      - run: npm publish -f
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  create-release:
    name: Create Release
    needs: publish-npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Extract dependency versions
        id: versions
        run: |
          PIXI_VN_JSON_VERSION=$(node -p "require('./package.json').dependencies['@drincs/pixi-vn-json']")
          INKJS_VERSION=$(node -p "require('./package.json').devDependencies['inkjs']")
          PIXI_VN_VERSION=$(node -p "require('./package.json').peerDependencies['@drincs/pixi-vn']")
          echo "pixi_vn_json=$PIXI_VN_JSON_VERSION" >> $GITHUB_OUTPUT
          echo "inkjs=$INKJS_VERSION" >> $GITHUB_OUTPUT
          echo "pixi_vn=$PIXI_VN_VERSION" >> $GITHUB_OUTPUT
      - uses: ncipollo/release-action@v1
        with:
          body: |
            Release ${{ github.ref }}

            ## Dependencies
            - **pixi-vn**: ${{ steps.versions.outputs.pixi_vn }}
            - **pixi-vn-json**: ${{ steps.versions.outputs.pixi_vn_json }}
            - **inkjs**: ${{ steps.versions.outputs.inkjs }}
